Sprint 7
dmamaievaa/java-kanban pull request #2
Opened 2024-05-24 14:01 UTC by dmamaievaa

2024-05-25 01:18 UTC, afomkina requested changes

2024-05-25 01:18 UTC, afomkina commented on src/manager/FileBackedTaskManager.java
> +    static TaskManager taskManager = Managers.getDefault();
Это поле лишнее

2024-05-25 01:18 UTC, afomkina commented on src/manager/FileBackedTaskManager.java
> +                                taskManager.findEpicStatus(epic);
Используй `fileBackedTaskManager`

2024-05-25 01:18 UTC, afomkina commented on src/manager/FileBackedTaskManager.java
> +        } catch (IOException e) {
Нужно избавиться от однобуквенных параметров во всем коде. Они делают код менее читаемым и его становится сложнее поддерживать

2024-05-25 01:18 UTC, afomkina commented on src/manager/FileBackedTaskManager.java
> +import java.io.*;
В коммерческой разработке не принято использовать `wildcard` в импортах.
Вот отличная [статья](https://struchkov.dev/blog/ru/using-wildcard-imports-in-java/#:~:text=%D0%98%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5%20%D0%BF%D0%BE%D0%B4%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BE%D1%87%D0%BD%D1%8B%D1%85%20%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82%D0%BE%D0%B2%20%D0%BD%D0%B8%D0%BA%D0%B0%D0%BA%20%D0%BD%D0%B5,%D1%81%D1%82%D0%BE%D0%BB%D0%BA%D0%BD%D1%83%D1%82%D1%8C%D1%81%D1%8F%20%D1%81%20%D0%BF%D1%80%D0%BE%D0%B1%D0%BB%D0%B5%D0%BC%D0%BE%D0%B9%20%D0%BA%D0%BE%D0%BD%D1%84%D0%BB%D0%B8%D0%BA%D1%82%D0%B0%20%D0%B8%D0%BC%D0%B5%D0%BD.) почему и как настроить идею, чтобы избавиться от `*`
Кстати, в IDEA есть отличное сочетание клавиш `Ctrl + Alt + O` - при нажатии сочетания в нужном классе автоматически оптимизируются импорты и удаляются ненужные

2024-05-25 01:18 UTC, afomkina commented on src/manager/Managers.java
> +    static File file = new File("resources/task.csv");
У поля должен быть модификатор доступа

2024-05-25 01:18 UTC, afomkina commented on test/manager/FileBackedTaskManagerTest.java
> +    TaskManager taskManager;
У поля не хватает модификатора доступа

2024-05-25 01:18 UTC, afomkina commented on test/manager/FileBackedTaskManagerTest.java
> +    @DisplayName("Create tasks from string and compare with manually created")
💪

2024-05-25 01:18 UTC, afomkina commented on test/manager/FileBackedTaskManagerTest.java
> +    @BeforeEach
Нужно добавить библиотеку JUnit в проект. Предполагаю, что папка с библиотеками не добавилась в репозиторий, так в файле `.gitignore` прописано правило игнорирования файлов типа `*.jar`. Нужно его удалить и закоммитить библиотеки в удаленный репозиторий

2024-05-25 12:31 UTC, dmamaievaa commented on src/manager/FileBackedTaskManager.java
> +import java.io.*;
Я оптимизирована импорты через идею и в этом классе "No unused imports found"
если я руками добавляю
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
идея сама замещает все это на import java.io.*, пришлось отключить в настройках все галки для импортов и тогда смогла обновить. Тут правда не подходит wildcard?

2024-05-25 14:28 UTC, dmamaievaa commented on test/manager/FileBackedTaskManagerTest.java
> +    @BeforeEach
Я чуть-чуть не понимаю зачем коммитить библиотеки? Это же не моя самописная история, а просто библиотека которая поставляется с самой идеей? Вроде как-то в самом начале я добавляла их через файлик практикума, а потом просто через project structure - libraries - и там JUnit
<img width="455" alt="project" src="https://github.com/dmamaievaa/java-kanban/assets/160703823/c538d70a-0a4f-4848-97ef-02836094d06a">

2024-05-26 13:44 UTC, afomkina commented on src/manager/FileBackedTaskManager.java
> +import java.io.*;
Да, нудно немного поправить настройки для idea, тогда она сама перестает автоматически схлопывать импорты. Молодец, что разобралась самостоятельно 🔥

FYI Оставлю тут скрин с настройками
<img width="984" alt="Screenshot 2024-05-26 at 10 43 52 AM" src="https://github.com/dmamaievaa/java-kanban/assets/43168217/945ea763-761b-437d-8ca1-63fa1fa0c459">

2024-05-26 13:47 UTC, afomkina commented on test/manager/FileBackedTaskManagerTest.java
> +    @BeforeEach
Ты права, это устаревший комментарий, раньше у нас не было автотестов на гитхабе для этого спринта, поэтому я по привычке прошу добавить библиотеки, когда вижу, что их нет. 
С другой стороны, можно немного покапать, чтобы понять как работает .gitignore

Добавлять библиотеки не нужно

2024-05-26 13:48 UTC, afomkina approved these changes

2024-05-26 14:34 UTC, merged